# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

[functions."run-daily-analysis"]
  # 매일 자정(UTC 기준)에 이 함수를 실행하라는 예약 명령어입니다.
  schedule = "0 0 * * *"

# ▼▼▼ 이 부분을 추가하세요! ▼▼▼
[[redirects]]
  from = "/"
  to = "/dashboard.html"
  status = 200