# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  [functions."analyze-store-reviews"]
    schedule = "0 0 * * *"

# ▼▼▼ 이 부분을 추가하세요! ▼▼▼
[[redirects]]
  from = "/"
  to = "/dashboard.html"
  status = 200